--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/poggit-orphanage/AlwaysSpawn
branches:
- master
projects:
  AlwaysSpawn:
    path: Plugin/New-API/AlwaysSpawn/
    icon: as.png
    projectId; 316
...
