name: AlwaysSpawn
authors: [Philip Shilling, Suerion]
version: 2.2.5
api: [3.0.0]
main: philipshilling\alwaysspawn\Loader
load: STARTUP
description: "Force your users to spawn every time they login!"
